
[project]
  name = "nft-project"
  authors = []
  telemetry = false
  cache_dir = "./.requirements"

[contracts.nft-factory]
  path = "contracts/nft-factory.clar"
  depends_on = ["nft-trait"]

[repl.analysis]
  passes = ["check_checker"]
  check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }